version: '3.1'

services:

  db:
    container_name: gostack_pg
    image: postgres:9.5.24-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432

  mongodb:
    container_name: gostack_mongo
    image: mongo:4.4.2-bionic
    restart: always
    ports:
      - 27017:27017

  redis:
    container_name: gostack_redis
    image: "redis:alpine"
    ports:
      - 6379:6379
